service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: default
  profile: jerry
  region: eu-central-1
  memorySize: 128
  reservedConcurrency: 5

functions:
  - ${file(functions.yml)}
